- hosts: all

  become: yes
  tasks:

  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
  - name: uninstall previous packages
    raw: for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
  
  - name: install required packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - wget
  # Add Docker's official GPG key:
  - name: create the keyring directory
    raw: sudo install -m 0755 -d /etc/apt/keyrings
  - name: download docker gpg keys 
    raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - name: modify acces
    raw: sudo chmod a+r /etc/apt/keyrings/docker.gpg

  # Add the repository to Apt sources:

  - name: Create Docker repository file
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: touch

  - name: Add Docker repository
    lineinfile:
      path: /etc/apt/sources.list.d/docker.list
      line: "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
      state: present
  
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes

  # Install Docker packages
  - name: install docker packages
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io 
        - docker-compose-plugin
        - docker-buildx-plugin
    state: present

  - name: Add the user to the docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

  - name: Start Docker service
    systemd:
      name: docker
      state: started
      enabled: yes

    